// design-system/components/src/react/Card/index.tsx
import type { HTMLAttributes } from 'react';
import cx from 'classnames';
import type { CardProps } from '../../shared/types/card';
import styles from '../../css/card.module.css';

type Props = CardProps & HTMLAttributes<HTMLDivElement>;

export function Card({ elevation = 'raised', children, className, ...rest }: Props) {
  return (
    <div className={cx(styles.card, styles[`card--${elevation}`], className)} {...rest}>
      {children}
    </div>
  );
}

// design-system/components/src/vue/Card/index.vue
<script setup lang="ts">
import { computed } from 'vue';
import cx from 'classnames';
import type { CardProps } from '../../shared/types/card';
import styles from '../../css/card.module.css';

const props = withDefaults(defineProps<CardProps>(), {
  elevation: 'raised',
});

const classes = computed(() => cx(styles.card, styles[`card--${props.elevation}`]));
</script>

<template>
  <div :class="classes">
    <slot />
  </div>
</template>
