// design-system/components/src/vue/Tag/index.vue
<script setup lang="ts">
import { computed } from 'vue';
import cx from 'classnames';
import type { TagProps } from '../../shared/types/tag';
import styles from '../../css/tag.module.css';

const props = withDefaults(defineProps<TagProps>(), {
  variant: 'default',
});

const classes = computed(() => cx(styles.tag, styles[`tag--${props.variant}`]));
</script>

<template>
  <span :class="classes">
    <slot />
  </span>
</template>

// design-system/components/src/react/Tag/index.tsx
import type { HTMLAttributes } from 'react';
import cx from 'classnames';
import type { TagProps } from '../../shared/types/tag';
import styles from '../../css/tag.module.css';

type Props = TagProps & HTMLAttributes<HTMLSpanElement>;

export function Tag({ variant = 'default', children, className, ...rest }: Props) {
  return (
    <span className={cx(styles.tag, styles[`tag--${variant}`], className)} {...rest}>
      {children}
    </span>
  );
}
