// design-system/components/src/vue/Button/index.vue
<script setup lang="ts">
import { computed } from 'vue';
import cx from 'classnames';
import type { ButtonProps } from '../../shared/types/button';
import styles from '../../css/button.module.css';

const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'primary',
  size: 'md',
  disabled: false,
});

const classes = computed(() =>
  cx(
    styles.button,
    styles[`button--${props.variant}`],
    styles[`button--${props.size}`],
    props.disabled && styles['button--disabled'],
  )
);
</script>

<template>
  <button :class="classes" :disabled="disabled">
    <slot />
  </button>
</template>

// design-system/components/src/react/Button/index.tsx
import type { ButtonHTMLAttributes } from 'react';
import cx from 'classnames';
import type { ButtonProps } from '../../shared/types/button';
import styles from '../../css/button.module.css';

type Props = ButtonProps & ButtonHTMLAttributes<HTMLButtonElement>;

export function Button({
  variant = 'primary',
  size = 'md',
  disabled = false,
  children,
  className,
  ...rest
}: Props) {
  return (
    <button
      className={cx(
        styles.button,
        styles[`button--${variant}`],
        styles[`button--${size}`],
        disabled && styles['button--disabled'],
        className,
      )}
      disabled={disabled}
      {...rest}
    >
      {children}
    </button>
  );
}
